#! /bin/sh

sxhkd &

# display
xrandr --output DVI-D-0 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-0 --off --output DP-5 --off --output DP-4 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-3 --mode 1920x1080 --pos 3840x0 --rotate normal --output DP-2 --off --output DP-1 --off --output DP-0 --off &


# if [ $(hostname) == 'nixos']; then
bspc monitor DP-4 -d I II III
bspc monitor DP-3 -d I II III
bspc monitor DVI-D-0 -d I II III
# else
#     bspc monitor -d 1 2 3 4 5 6 7 8 9
# fi

bspc config border_width        4
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config borderless_monocle true
bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a feh state=floating

# Application
xcape -e "Caps_Lock=Escape" &
compton -b &
unclutter &
# emacs --daemon &


polybar main &
polybar left &
polybar right &


emacs --daemon &
