#! /bin/sh

sxhkd &

# display
if [[ $(hostname) == 'nixos' ]]; then
    xrandr --output DVI-D-0 --mode 1920x1080 --pos 0x0 --rotate normal \
	   --output HDMI-0 --off \
	   --output DP-5 --off \
	   --output DP-4 --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
	   --output DP-3 --mode 1920x1080 --pos 3840x0 --rotate normal \
	   --output DP-2 --off \
	   --output DP-1 --off \
	   --output DP-0 --off &
    bspc monitor DP-4    -d 1 2 3 4 5 6 7 8 9 10
    bspc monitor DP-3    -d 1 2 3 4 5 6 7 8 9 10
    bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9 10
    polybar main  &
    polybar left  &
    polybar right &
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width	    4
bspc config window_gap		    6
bspc config focused_border_color    "#91B496"
bspc config split_ratio		    0.5
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config borderless_monocle	    true
bspc config pointer_follows_monitor true
bspc config single_monocle	    true
bspc config borderless_monocle	    false
bspc config gapless_monocle	    false

bspc rule -a Gimp	       state=floating follow=on
bspc rule -a Lxappearance      state=floating
bspc rule -a Kupfer.py	       focus=on
bspc rule -a Screenkey	       manage=off
bspc rule -a Gnuplot	       state=floating
bspc rule -a mpv	       state=floating
bspc rule -a feh	       state=floating
bspc rule -a URxvt:volumeFloat state=floating follow=on rectangle=960x540+480+270
bspc rule -a URxvt:rangerFloat state=floating follow=on rectangle=960x540+480+270
bspc rule -a URxvt:htopFloat   state=floating follow=on rectangle=960x540+480+270
bspc rule -a URxvt:musicFloat  state=floating follow=on rectangle=960x540+480+270
bspc rule -a Emacs:org-agenda  state=floating follow=on rectangle=960x540+480+270

# Application
$HOME/.fehbg
wmname LG3D
xcape -e "Caps_Lock=Escape" &
compton -b &
urxvtd &
unclutter &
emacs --daemon &
