#!/bin/sh
yadm decrypt
echo "cloning xmonad.."
git clone git@github.com:peterzky/myxmonad.git $HOME/.xmonad
echo "cloning emacs.d.."
rm -rf $HOME/.emacs.d
git clone git@github.com:peterzky/emacs.d.git $HOME/.emacs.d
echo "cloning nix-config..."
git clone git@gitlab.com:peterzky/nix-config.git $HOME/nixos
